const Donor=require("../model/donorModel"),Donation=require("../model/donationModel"),Blood=require("../model/bloodModel"),Request=require("../model/requestModel");
const dashboard=async(req,res)=>{try{
 const [donors,donations,pendingRequests,inventory]=await Promise.all([Donor.countDocuments(),Donation.countDocuments(),Request.countDocuments({status:"Pending"}),Blood.find().sort({bloodGroup:1})]);
 res.render("admin/dashboard",{stats:{donors,donations,pendingRequests,totalUnits:inventory.reduce((s,x)=>s+x.unitsAvailable,0)},inventory});
}catch(e){console.log(e);res.status(500).render("error",{message:"Could not load admin dashboard."});}};
const requests=async(req,res)=>{try{res.render("admin/requests",{requests:await Request.find().populate("requester","name email").sort({createdAt:-1})});}catch(e){res.status(500).render("error",{message:"Could not load requests."});}};
const donors=async(req,res)=>{try{res.render("admin/donors",{donors:await Donor.find().populate("user","name email phone").sort({createdAt:-1})});}catch(e){res.status(500).render("error",{message:"Could not load donors."});}};
const updateInventory=async(req,res)=>{try{await Blood.findOneAndUpdate({bloodGroup:req.body.bloodGroup},{unitsAvailable:Number(req.body.unitsAvailable),lowStockLimit:Number(req.body.lowStockLimit)},{upsert:true,new:true});res.redirect("/admin/dashboard");}catch(e){res.status(500).render("error",{message:"Could not update inventory."});}};
const status=async(id,s,res)=>{try{const r=await Request.findById(id);if(!r)return res.status(404).render("error",{message:"Request not found."});r.status=s;await r.save();res.redirect("/admin/requests");}catch(e){res.status(500).render("error",{message:"Could not update request."});}};
const approveRequest=(req,res)=>status(req.params.id,"Approved",res),rejectRequest=(req,res)=>status(req.params.id,"Rejected",res);
const fulfillRequest=async(req,res)=>{try{const r=await Request.findById(req.params.id),b=r&&await Blood.findOne({bloodGroup:r.bloodGroup});if(!r)return res.status(404).render("error",{message:"Request not found."});if(r.status!=="Approved")return res.status(400).render("error",{message:"Only approved requests can be fulfilled."});if(!b||b.unitsAvailable<r.unitsRequired)return res.status(400).render("error",{message:"Not enough blood units available."});b.unitsAvailable-=r.unitsRequired;await b.save();r.status="Fulfilled";await r.save();res.redirect("/admin/requests");}catch(e){res.status(500).render("error",{message:"Could not fulfill request."});}};
module.exports={dashboard,requests,donors,updateInventory,approveRequest,rejectRequest,fulfillRequest};
